image_distro: centos-minimal
image_release:
image_target_name:
ipa_branch_path: '{{ zuul.branch | replace("/", "-") }}'
ipa_source_path: '{{ ansible_user_dir }}/src/opendev.org/openstack/ironic-python-agent'
requirements_path: '{{ ansible_user_dir }}/src/opendev.org/openstack/requirements'
ipa_raw_dir: '{{ ansible_user_dir }}/src/opendev.org/openstack/ironic-python-agent/UPLOAD_RAW'
ipa_tar_dir: '{{ ansible_user_dir }}/src/opendev.org/openstack/ironic-python-agent/UPLOAD_TAR'
dib_extra_args:
dib_from_source: true
dib_no_tmpfs: 0
extra_elements: ["dynamic-login"]
